_BASE_: ../Base-bagtricks.yml
INPUT:
  SIZE_TRAIN: [128, 256]
  SIZE_TEST: [128, 256]
DATASETS:
  NAMES: ("AIC",)
  TESTS: ("AIC",)
SOLVER:
  IMS_PER_BATCH: 128
  MAX_EPOCH: 120
  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 3
  IMS_PER_BATCH: 256
  PRECISE_BN:
    DATASET: AIC23
OUTPUT_DIR: logs/aic23/bagtricks_R50
